### ISSUE TITLE
FEATURE REQUEST: add voice selection for ai

### ISSUE THREAD

**Issue by 1im** [10Dozen/dzn_gear#26]
Greetings,

We would like to suggest you a new feature for dzn_gear, that will make missions against specific factions more authentic, namely, the ability to choose a voice for an AI, if it's possible, so we would not be limited to unit classnames that usually get borked.

Best regards,
LeeMantee

**Comment by 10Dozen** [comment]
Hello,

it's a great feature, that i planned to implement long time ago, but then i forgot about it.
So yeah, will look into it.

I think it will be like additional kit array item, e.g.
["< IDENTITY>>>", @Face, @Voice, @Name]
, where @Face, @Voice and @Name are single item (String) or array of items (randomized will be picked, like other gear kit parameters). #defines are also available.

But not even know how to implement this, so no release date for now.

**Comment by 1im** [comment]
Thanks for prompt response!

I hope you will find a solution, for now on, many thanks from our community, we absolutely adore your work

Keep it up!

Best regards,
LeeMantee

**Comment by 10Dozen** [comment]
http://i3.kym-cdn.com/photos/images/facebook/000/345/169/bc7.png

**Comment by 10Dozen** [comment]
Please, try [2.2-Identity branch](https://github.com/10Dozen/dzn_gear/tree/2.2-Identity). 

By default Identity is not copied with kit (to avoid twins). To get Identity settings use Ctrl + I combination and add copied code to your kit.

Please, test 2.2 version and pay attention to Multiplayer compatibility (looks like identity is not broadcasts over network, but not sure for now).

There are also few fixes/updates of Edit Mode, so don't panic =) Arsenal now allows you to choose  face and voice, Gear Totals section is displayed while arsenal is opened.

**Comment by 10Dozen** [comment]
Implemented and tested.
Have fun.
