### ISSUE TITLE
Default NVG for autoassigned items

### ISSUE THREAD

**Issue by 1im** [10Dozen/dzn_gear#30]
Greetings, it would be amazing, if NIGHT_ITEM nvg's are going to be added automatically, along with the rest of auto-assigned items, it will ensure the missions day/night compatability and should not bring too much pain

I would suggest to add a line like **#define give_nvg [NIGHT_ITEM["NVGoggles_OPFOR"]** in defines section, aswell as adding **,give_nvg** in the end of assigned items, to ensure compatability and exclude any needs of rewriting the code base, yay!

**Comment by 10Dozen** [comment]
Fixed in https://github.com/10Dozen/dzn_gear/tree/dzn-gear-pip-2.5

@1im , plz test.

Define Uniform/Assigned items in Settings.sqf, then use PgUp and PgDown to cycle switch mode of Uniform/Assigned items replacement
