### ISSUE TITLE
Randomization doesn't work for cargo kits

### ISSUE THREAD

**Issue by Temon20p** [10Dozen/dzn_gear#52]
If I create cargo kit with , for example, weapon ["arifle_AK12_F",1] it's works fine. But then I want to make kit spawn random weapon [WEAPONS_LIST,1] it shows error that array is not supported type.

23:40:19 Error in expression <gory = (_this select 1) select 0;
{_box addWeaponCargoGlobal _x;} forEach _categ>
23:40:19   Error position: <addWeaponCargoGlobal _x;} forEach _categ>
23:40:19   Error Type array, expected String

**Comment by 10Dozen** [comment]
Yeah, cargo randomization is not implementd. I will look into it, but not sure when

**Comment by 10Dozen** [comment]
Please, try https://github.com/10Dozen/dzn_gear/tree/v2.9

Item randomization should work for items described like: `[["Item1", "Item2"], 2]`
